when:
  event: tag

variables:
  - &golang_image 'docker.io/golang:1.22.2'

steps:
  vendor:
    image: *golang_image
    commands:
      - go mod vendor

  build-tarball:
    depends_on:
      - vendor
    image: *golang_image
    commands:
      - make build-tarball

  build:
    depends_on:
      - vendor
    image: *golang_image
    commands:
      - make release

  checksums:
    depends_on:
      - build
      - build-tarball
    image: *golang_image
    commands:
      - make release-checksums

  release-dryrun:
    depends_on:
      - checksums
    image: *golang_image
    commands:
      - ls -la dist/*.*
      - cat dist/checksums.txt

  release:
    depends_on:
      - checksums
    image: docker.io/plugins/github-release
    secrets:
      - source: github_token
        target: github_release_api_key
    settings:
      files:
        - dist/*.tar.gz
        - dist/*.deb
        - dist/*.rpm
        - dist/checksums.txt
      title: ${CI_COMMIT_TAG##v}